CREATE TABLE IF NOT EXISTS condition_travail (
    id                      BIGSERIAL PRIMARY KEY,
    nom                     VARCHAR(255)   NOT NULL,
    nb_chauffeurs           INT            NOT NULL DEFAULT 1,
    type_programme          VARCHAR(50),
    heure_debut_service     VARCHAR(10)    NOT NULL,
    heure_fin_service       VARCHAR(10)    NOT NULL,
    mode_alternance         VARCHAR(30),
    jours_alternance        INT,
    date_debut_alternance   DATE,
    jour_salaire            VARCHAR(20),
    objectif_recette        NUMERIC(15, 2) NOT NULL,
    type_recette            VARCHAR(30)    NOT NULL,
    montant_jour_salaire    NUMERIC(15, 2),
    mode_encaissement       VARCHAR(30)    NOT NULL,
    frequence_versement     VARCHAR(30)    NOT NULL,
    jour_versement          VARCHAR(20),
    heure_versement         VARCHAR(10)    NOT NULL,
    created_at              TIMESTAMP,
    updated_at              TIMESTAMP,
    CONSTRAINT chk_condition_travail_type_recette      CHECK (type_recette IN ('MONTANT_FIXE', 'MONTANT_REEL')),
    CONSTRAINT chk_condition_travail_mode_encaissement CHECK (mode_encaissement IN ('ESPECES', 'MOBILE_MONEY', 'LES_DEUX')),
    CONSTRAINT chk_condition_travail_frequence_versement CHECK (frequence_versement IN ('JOURNALIER', 'HEBDOMADAIRE'))
);
