spring:
  flyway:
    enabled: false
    baseline-on-migrate: true
    out-of-order: true
    ignore-migration-patterns: "*:missing"
    #locations: classpath:db/migration/flyway/schema,classpath:db/migration/flyway/jdd/reference,classpath:db/migration/flyway/jdd/dev

logging:
  level:
    org.flywaydb: DEBUG
